<?php

namespace Xxx\ClientBundle\Repository;

/**
 * FilteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
