<?php

namespace Xxx\ClientBundle\Repository;

/**
 * InterventionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionReportRepository extends \Doctrine\ORM\EntityRepository
{
}
