<?php

namespace Xxx\ClientBundle\Repository;

/**
 * ProjectStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStateRepository extends \Doctrine\ORM\EntityRepository
{
}
