<?php

namespace Xxx\ClientBundle\Repository;

/**
 * RaisingMoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaisingMoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
