<?php

namespace Xxx\ClientBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser($user, $returnQueryBuilder)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('t', 'p')
            ->from($this->_entityName, 't')
            ->leftJoin('t.project', 'p')
            ->leftJoin('p.customer', 'u')
            ->leftJoin('p.EAteamUser', 'EAu')
            ->where('u.id = :user_id')
            ->orWhere('EAu.id = :user_id')
            ->setParameter('user_id', $user->getId());

        if ($returnQueryBuilder)
            return $queryBuilder;

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
