<?php

namespace Xxx\ClientBundle\Repository;

/**
 * UserDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
