# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        clientUser:
            entity:
                class: Xxx\ClientBundle\Entity\User
                property: email
    role_hierarchy:
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
            ROLE_ADMIN:
             - ROLE_USER

    encoders:
        Xxx\ClientBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|console)|css|images|js)/
            security: false
            
        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
